name: pyinstaller
on: workflow_dispatch

jobs:
    build-on-windows:
        runs-on: windows-2022
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: install installer
              run: pip install pyinstaller
            - name: build exe
              run: pyinstaller sha256.py -F
            - name: upload exe file
              uses: actions/upload-artifact@v4
              with:
                name: sha256-windows-exe
                path: dist/sha256.exe # 上傳文件的路徑