name: workflow_secrets
on: workflow_dispatch

env: 
    DB_U: ${{ vars.DB_USERNAME }} # 用戶名 # test
    DB_P: ${{ secrets.DB_PASSWORD }} # 對密碼進行保護

jobs:
    test-secrets:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: check env u
              run: echo "u=${{ env.DB_U }}"
            - name: check env p
              # run: echo "p=${{ env.DB_P }}"
              run: echo "p=${{ secrets.DB_PASSWORD }}" # secrets值要足夠複雜
            - name: test with python
              run: python secrets.py